# Generated by Django 5.1.4 on 2024-12-07 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_item_image'),
        ('mainApp', '0003_cart_quantity'),
    ]

    operations = [
    ]
