# Generated by Django 5.1.3 on 2024-12-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_alter_cart_image_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='logout',
        ),
    ]
