# Generated by Django 5.1.4 on 2024-12-07 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_merge_0003_alter_item_image_0003_cart_quantity'),
        ('mainApp', '0005_remove_profile_logout'),
    ]

    operations = [
    ]
